/**
 * PR 审查集成模块
 *
 * 将验证结果格式化为 PR 评论，支持 Markdown 表格、行级评论、
 * 超阈值折叠以及多语言（中文/英文）输出。
 */

import type { Finding, VerifierResult, SynthesizedResult } from '../schemas/verifier-result.js';

// ─── 配置接口 ───────────────────────────────────────────

/** PR 评论生成配置 */
export interface PRReviewConfig {
  /** 是否在评论中显示分数 */
  include_score: boolean;
  /** 是否显示详细发现 */
  include_findings: boolean;
  /** 最大显示发现数 */
  max_findings: number;
  /** 超过此数折叠显示 */
  collapse_threshold: number;
  /** 评论语言 */
  language: 'en' | 'zh';
}

// ─── 输出接口 ───────────────────────────────────────────

/** PR 评论结构 */
export interface PRComment {
  /** Markdown 格式的评论内容 */
  body: string;
  /** 审查状态 */
  status: 'approved' | 'changes_requested' | 'commented';
  /** 行级别评论列表 */
  file_comments: FileComment[];
}

/** 文件行级评论 */
export interface FileComment {
  /** 文件路径 */
  path: string;
  /** 行号 */
  line: number;
  /** 评论内容 */
  body: string;
  /** 严重程度 */
  severity: 'error' | 'warning' | 'info';
}

// ─── 默认配置 ───────────────────────────────────────────

/** 默认 PR 审查配置 */
const DEFAULT_CONFIG: PRReviewConfig = {
  include_score: true,
  include_findings: true,
  max_findings: 20,
  collapse_threshold: 5,
  language: 'zh',
};

// ─── 多语言文案 ─────────────────────────────────────────

/** 中文文案 */
const ZH_LABELS = {
  title: '## 并行验证报告',
  verifier_type: '验证器类型',
  status: '状态',
  score: '分数',
  findings_title: '### 发现列表',
  no_findings: '未发现问题',
  collapsed_prefix: '展开查看全部',
  findings_suffix: '条发现',
  overall: '### 综合评估',
  overall_score: '综合分数',
  overall_status: '综合状态',
  summary: '总结',
  signature: '🤖 Generated by parallel-harness',
  truncated: '（已截断，仅显示前 {n} 条）',
} as const;

/** 英文文案 */
const EN_LABELS = {
  title: '## Parallel Verification Report',
  verifier_type: 'Verifier Type',
  status: 'Status',
  score: 'Score',
  findings_title: '### Findings',
  no_findings: 'No findings',
  collapsed_prefix: 'Show all',
  findings_suffix: 'findings',
  overall: '### Overall Assessment',
  overall_score: 'Overall Score',
  overall_status: 'Overall Status',
  summary: 'Summary',
  signature: '🤖 Generated by parallel-harness',
  truncated: '(truncated, showing first {n})',
} as const;

// ─── 状态 emoji 映射 ────────────────────────────────────

/** 验证状态对应的 emoji */
const STATUS_EMOJI: Record<string, string> = {
  pass: '✅',
  fail: '❌',
  warn: '⚠️',
  skip: '⏭️',
};

/** 严重程度对应的 emoji */
const SEVERITY_EMOJI: Record<string, string> = {
  error: '❌',
  warning: '⚠️',
  info: 'ℹ️',
};

// ─── 验证器类型标签映射 ─────────────────────────────────

/** 验证器类型的中文标签 */
const VERIFIER_LABELS_ZH: Record<string, string> = {
  test: '测试验证',
  review: '代码审查',
  security: '安全扫描',
  perf: '性能测试',
};

/** 验证器类型的英文标签 */
const VERIFIER_LABELS_EN: Record<string, string> = {
  test: 'Test',
  review: 'Code Review',
  security: 'Security Scan',
  perf: 'Performance',
};

// ─── PRReviewer 类 ──────────────────────────────────────

/**
 * PR 审查器：将 SynthesizedResult 转换为结构化的 PR 评论。
 *
 * 使用方式：
 * ```ts
 * const reviewer = new PRReviewer({ language: 'zh' });
 * const comment = reviewer.generateReview(synthesized);
 * // comment.body 即为 Markdown 格式的 PR 评论
 * ```
 */
export class PRReviewer {
  /** 合并后的配置 */
  private readonly config: PRReviewConfig;

  /**
   * 构造 PR 审查器
   * @param config - 可选的部分配置，未指定字段使用默认值
   */
  constructor(config?: Partial<PRReviewConfig>) {
    this.config = { ...DEFAULT_CONFIG, ...config };
  }

  /**
   * 从综合结果生成完整的 PR 评论
   * @param synthesized - 多验证器汇总后的综合结果
   * @returns PR 评论对象，包含 Markdown 正文、审查状态和行级评论
   */
  generateReview(synthesized: SynthesizedResult): PRComment {
    const labels = this.getLabels();
    const sections: string[] = [];

    // 标题
    sections.push(labels.title);
    sections.push('');

    // 摘要表格
    sections.push(this.formatSummary(synthesized));
    sections.push('');

    // 综合评估
    sections.push(labels.overall);
    sections.push('');
    sections.push(
      `- **${labels.overall_status}**: ${STATUS_EMOJI[synthesized.overall_status] ?? ''} ${synthesized.overall_status}`,
    );
    if (this.config.include_score) {
      sections.push(
        `- **${labels.overall_score}**: ${synthesized.overall_score}/100`,
      );
    }
    sections.push(`- **${labels.summary}**: ${synthesized.summary}`);
    sections.push('');

    // 详细发现
    if (this.config.include_findings) {
      const allFindings = synthesized.results.flatMap(r => r.findings);
      if (allFindings.length > 0) {
        sections.push(this.formatFindings(allFindings));
        sections.push('');
      }
    }

    // 签名
    sections.push('---');
    sections.push(labels.signature);

    // 组装输出
    const body = sections.join('\n');
    const status = this.getReviewStatus(synthesized);
    const file_comments = this.generateFileComments(synthesized.results);

    return { body, status, file_comments };
  }

  /**
   * 格式化摘要表格
   * @param synthesized - 综合结果
   * @returns Markdown 表格字符串
   */
  formatSummary(synthesized: SynthesizedResult): string {
    const labels = this.getLabels();
    const verifierLabels =
      this.config.language === 'zh' ? VERIFIER_LABELS_ZH : VERIFIER_LABELS_EN;

    // 表头
    const header = this.config.include_score
      ? `| ${labels.verifier_type} | ${labels.status} | ${labels.score} |`
      : `| ${labels.verifier_type} | ${labels.status} |`;

    const separator = this.config.include_score
      ? '| --- | --- | --- |'
      : '| --- | --- |';

    // 表体
    const rows = synthesized.results.map(result => {
      const typeLabel = verifierLabels[result.verifier_type] ?? result.verifier_type;
      const statusEmoji = STATUS_EMOJI[result.status] ?? '';
      const statusCell = `${statusEmoji} ${result.status}`;

      return this.config.include_score
        ? `| ${typeLabel} | ${statusCell} | ${result.score}/100 |`
        : `| ${typeLabel} | ${statusCell} |`;
    });

    return [header, separator, ...rows].join('\n');
  }

  /**
   * 格式化发现列表
   * @param findings - 所有验证器发现的问题
   * @returns Markdown 格式的发现列表（可能包含折叠）
   */
  formatFindings(findings: Finding[]): string {
    const labels = this.getLabels();
    const lines: string[] = [];

    lines.push(labels.findings_title);
    lines.push('');

    // 截断
    const limited = findings.slice(0, this.config.max_findings);
    const isTruncated = findings.length > this.config.max_findings;

    // 判断是否需要折叠
    const shouldCollapse = limited.length > this.config.collapse_threshold;

    if (shouldCollapse) {
      // 先显示 collapse_threshold 条，其余折叠
      const visible = limited.slice(0, this.config.collapse_threshold);
      const collapsed = limited.slice(this.config.collapse_threshold);

      for (const f of visible) {
        lines.push(this.formatSingleFinding(f));
      }

      lines.push('');
      lines.push(
        `<details><summary>${labels.collapsed_prefix}（${collapsed.length} ${labels.findings_suffix}）</summary>`,
      );
      lines.push('');
      for (const f of collapsed) {
        lines.push(this.formatSingleFinding(f));
      }
      lines.push('');
      lines.push('</details>');
    } else {
      for (const f of limited) {
        lines.push(this.formatSingleFinding(f));
      }
    }

    // 截断提示
    if (isTruncated) {
      lines.push('');
      lines.push(
        labels.truncated.replace('{n}', String(this.config.max_findings)),
      );
    }

    return lines.join('\n');
  }

  /**
   * 从验证结果中提取行级文件评论
   * @param results - 各验证器的运行结果
   * @returns 文件行级评论数组
   */
  generateFileComments(results: VerifierResult[]): FileComment[] {
    const comments: FileComment[] = [];

    for (const result of results) {
      for (const finding of result.findings) {
        // 只有同时具有文件路径和行号的发现才能生成行级评论
        if (finding.file && finding.line != null) {
          comments.push({
            path: finding.file,
            line: finding.line,
            body: this.formatFileCommentBody(finding, result),
            severity: finding.severity,
          });
        }
      }
    }

    return comments;
  }

  /**
   * 根据综合结果判断审查状态
   *
   * 判断规则：
   * - overall_status 为 'fail' 或 overall_score < 60 → changes_requested
   * - overall_status 为 'pass' 且 overall_score >= 80 → approved
   * - 其他情况 → commented
   *
   * @param synthesized - 综合结果
   * @returns 审查状态
   */
  getReviewStatus(
    synthesized: SynthesizedResult,
  ): 'approved' | 'changes_requested' | 'commented' {
    if (
      synthesized.overall_status === 'fail' ||
      synthesized.overall_score < 60
    ) {
      return 'changes_requested';
    }

    if (
      synthesized.overall_status === 'pass' &&
      synthesized.overall_score >= 80
    ) {
      return 'approved';
    }

    return 'commented';
  }

  // ─── 私有辅助方法 ───────────────────────────────────────

  /**
   * 获取当前语言对应的文案
   */
  private getLabels() {
    return this.config.language === 'zh' ? ZH_LABELS : EN_LABELS;
  }

  /**
   * 格式化单条发现为 Markdown 列表项
   * @param finding - 单条发现
   * @returns 格式化后的字符串
   */
  private formatSingleFinding(finding: Finding): string {
    const emoji = SEVERITY_EMOJI[finding.severity] ?? '';
    const location = finding.file
      ? finding.line != null
        ? ` (\`${finding.file}:${finding.line}\`)`
        : ` (\`${finding.file}\`)`
      : '';
    const rule = finding.rule ? ` [${finding.rule}]` : '';

    return `- ${emoji} ${finding.message}${location}${rule}`;
  }

  /**
   * 格式化行级评论的正文
   * @param finding - 单条发现
   * @param result - 所属的验证器结果
   * @returns 评论正文
   */
  private formatFileCommentBody(
    finding: Finding,
    result: VerifierResult,
  ): string {
    const emoji = SEVERITY_EMOJI[finding.severity] ?? '';
    const verifierLabels =
      this.config.language === 'zh' ? VERIFIER_LABELS_ZH : VERIFIER_LABELS_EN;
    const verifierLabel =
      verifierLabels[result.verifier_type] ?? result.verifier_type;
    const rule = finding.rule ? `\n规则: \`${finding.rule}\`` : '';

    return `${emoji} **[${verifierLabel}]** ${finding.message}${rule}`;
  }
}
